name: Build SukiSU Sultan
on:
  workflow_dispatch:
jobs:
  build-pixel9proxl:
    uses: ./.github/workflows/sultan.yml
    with:
      codename: "zumapro"
      repo: "android_kernel_google_zumapro"
      android_version: "android14"
      kernel_version: "6.1"
